adnat/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'static_pages/index'
  resources :organisations do
    resources :users #do
      #resources :shifts
    #end 
    resources :shifts
  end

  #Custom routing.
  get 'organisations/join/:id', to: 'users#join'
  get 'organisations/leave/:id', to: 'users#leave'

  resources :users
  resources :shifts
  root 'static_pages#index'
end

adnat/app/views/layouts/partials/_card.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title text-center"><%=name%></h5>
    <p class="card-text text-center">
      <%= link_to edit_organisation_path(id) do %>
        Edit 
      <% end %>
      | 
      <%= link_to "organisations/join/#{id}" do %>
        Join
      <% end %>
    </p>
  </div>
</div>

adnat/app/views/layouts/partials/_navbar_guest.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <img src="https://openclipart.org/image/2400px/svg_to_png/24793/Anonymous-Paper-4-icon.png" class="nav_logo" alt="Logo"> </div>
  Adnat - Challenge
</a>
<div>
  <h6 style="padding-right: 50px;"><%= link_to 'Log in', new_user_session_path%> <span style="padding: 10px">| </span>
    <%= link_to 'Register', new_user_registration_path%></h6>
</div>
</nav>

adnat/app/views/layouts/partials/_navbar_user.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <img src="https://openclipart.org/image/2400px/svg_to_png/24793/Anonymous-Paper-4-icon.png" class="nav_logo" alt="Logo"> </div>
  Adnat - Challenge
</a>
<form class="form-inline">
  Welcome&nbsp <strong> <%= current_user.email %> </strong> <span style="padding: 10px">| </span>
  <%= link_to 'Dashboard', organisations_path %><span style="padding: 10px">| </span>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> <span style="padding: 10px">| </span>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link', :style => 'margin-right: 40px'%>
</form>
</nav>