adnat/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'static_pages/index'
  resources :organisations do
    resources :users #do
      #resources :shifts
    #end 
    resources :shifts
  end

  #Custom routing.
  get 'organisations/join/:id', to: 'users#join'
  get 'organisations/leave/:id', to: 'users#leave'

  resources :users
  resources :shifts
  root 'static_pages#index'
end

adnat/app/models/organisation.rb
class Organisation < ApplicationRecord
    #Must have a name of minimum 1 character.
    validates :name, presence: true, length: { in: 1..30 }

    #Must have an hourly rate attached
    validates :hourly_rate, presence: true

    #Referential Constraints
    has_many :users
    
end

adnat/app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController

    #Display all Organisations
    def index
        if(current_user.organisation_id.nil?)
            @organisation = Organisation.all
        else 
            @organisation = Organisation.find(current_user.organisation_id)
        end 

        @creationOrganisation = Organisation.new
    end

    #Initial Creation of new organisation for form.
    def new
        @organisation = Organisation.new
    end


    #Display Organisation by given ID Paramater
    def show
        if check_validity(params[:id])
            @organisation = Organisation.find(params[:id])
        end
    end 

    #Edit an existing organisation
    def edit
        if check_validity(params[:id])
            @organisation = Organisation.find(params[:id])
        end
    end

    #Create and Join a new Organisation
    def create
        @organisation = Organisation.new(organisation_params)
        
        if @organisation.save
            flash[:notice] = "Success! New Organisation Created"
            redirect_to "/organisations/join/#{@organisation.id}"
        else 
            flash[:alert] = "Error on Organisation Creation. Check if a field is blank"
            redirect_to index
        end 
    end

    #Update the model through PATCH call. Called from Edit.html.erb
    def update
        @organisation = Organisation.find(params[:id])

        if @organisation.update(organisation_params)
            flash[:notice] = "Success! Organisation Updated"
            redirect_to @organisation
        else
            render 'edit'
        end
    end

    # Destroy Organisation with given ID.
    # Note: Currently no link to destory an organisation. This would be another feature with
    # CANCAN for permissions. Only the creator of the organisation can delete.
    def destroy
        @organisation = Organisation.find(params[:id])
        if @organisation.destroy
            flash[:notice] = "Organisation Removed"
            render 'new'
        else
            redirect_to organisation_path
        end 
    end

    # Create Strict requirements for what is entered into the model
    # and ultimately the Database
    private
    def organisation_params
        params.require(:organisation).permit(:name, :hourly_rate)
    end

    # DRYING up some code
    # Checks validity of an organisation. If it doesn't exist. Will just redirect
    private
    def check_validity(id)
        begin
            Organisation.find(id)
            return true
        rescue
            print "Bad Organisation ID - Redirecting \n"
            redirect_to organisations_path
            return false
        end 
    end


end

adnat/app/helpers/organisations_helper.rb
module OrganisationsHelper
end

adnat/app/views/organisations/_form.html.erb
<div class="container"><br>
  <div class="row justify-content-md-center">
    <div class="col col-md-5">
      <%= form_with(model: @organisation, local: true) do |organisation_form| %>
        <div class="card text-center">
          <div class="card-body" >
            <h3 class="card-title text-center">Edit Organisation</h3>
            <p class="card-text text-center"><br>
              <%= organisation_form.label :name %>
              <%= organisation_form.text_field :name %>
              <br>
              <%= organisation_form.label :hourly_rate %>
              <%= organisation_form.text_field :hourly_rate %>
              <br>
              <%= organisation_form.submit "Update" %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <% if @organisation.errors.any? %>
      <div id="error_explanation">
        <% @organisation.errors.full_messages.each do |msg| %>
          <span style="color: red"><strong>Notice: </strong></span>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

adnat/app/views/organisations/index.html.erb
<!-- If User not in Organisation display all organisations -->
<% if current_user.organisation_id.nil?%>
  <div class="container" >
    <div class="organisation-header">
      <br>
      <br>
      <h5>You aren't a member of any organisations. Join an existing one or create a new one.</h5>
    </div>
    <div class="card-columns">
      <% @organisation.each do |organisation| %>
        <%= render 'layouts/partials/card', id: organisation.id, name: organisation.name%>
      <% end %>
    </div>
    <!-- Not in one. So create an organisation -->
    <hr>
    <h3> Create Organisation </h3>
    <%= form_for (@creationOrganisation) do |organisation_form| %>
      <% if @creationOrganisation.errors.any? %>
        <div id="error_explanation">
          <% @creationOrganisation.errors.full_messages.each do |msg| %>
            <span style="color: red"><strong>Notice: </strong></span>
            <%= msg %><br>
          <% end %>
        </div>
      <% end %>
      <p>
        <%= organisation_form.label :name %>
        <%= organisation_form.text_field :name %>
        <br>
        <%= organisation_form.label :hourly_rate %>
        <%= organisation_form.text_field :hourly_rate %>
        <br>
        <%= organisation_form.submit "Create and Join" %>
      </p>
    <% end %>
    <!-- Else -->
  <% else %>
    <br>
    <br>
    <div class="container" >
      <div class="organisation-header">
        <h4> Organisation you've joined: <%= @organisation.name %> </h4>
        <br>
      </div>
      <div class="card-deck">
        <div class="card">
          <div class="card-body">
            <%= link_to organisation_shifts_path(@organisation.id) do %>
              <h5 class="card-title">View Shifts</h5>
            <% end %>
            <p class="card-text"> View, Add and update shifts at this organisation.</p>
            <p class="card-text"><small class="text-muted">Shift Last updated 3 mins ago</small></p>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <%= link_to edit_organisation_path(@organisation.id) do %>
              <h5 class="card-title">Edit Organisation</h5>
            <% end %>
            <p class="card-text"> Leave the Organisation. You'll have to rejoin to view the shifts.</p>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <%= link_to "organisations/leave/#{@organisation.id}" do %>
              <h5 class="card-title">Leave Organisation</h5>
            <% end %>
            <p class="card-text"> Leave the Organisation. You'll have to rejoin to view the shifts.</p>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Placeholder Link</h5>
            <p class="card-text"> A link left here to beef up the layout on the page.</p>
          </div>
        </div>
      </div>
    </div>
  <% end %>

adnat/app/views/organisations/new.html.erb
<h2> New Organisation </h2>
<%= render 'form' %>
<%= link_to 'Back', organisation_path%>

adnat/app/views/organisations/show.html.erb
<div class="container"><br>
  <div class="row justify-content-md-center">
    <div class="col col-md-5">
      <div class="card text-center">
        <div class="card-body" >
          <h3 class="card-title text-center">View Organisation</h3>
          <p class="card-text text-center"><br>
            <strong>Organisation Name:</strong> <%=@organisation.name%><br>
            <strong>Hourly Rate: </strong><%= @organisation.hourly_rate%><br>
            <br>
            <%= link_to edit_organisation_path(@organisation.id) do %>
              Edit 
            <% end %>
            <% if current_user.organisation_id.nil?%>
              | 
              <%= link_to "organisations/join/#{@organisation_id}" do %>
                Join
              <% end %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>