adnat/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'static_pages/index'
  resources :organisations do
    resources :users #do
      #resources :shifts
    #end 
    resources :shifts
  end

  #Custom routing.
  get 'organisations/join/:id', to: 'users#join'
  get 'organisations/leave/:id', to: 'users#leave'

  resources :users
  resources :shifts
  root 'static_pages#index'
end

adnat/app/models/shift.rb
class Shift < ApplicationRecord

  validates :start, presence: true #Must have a start time.
  validates :finish, presence: true #Must have an end time
  validates :breaklength, presence: true, numericality: { greater_than_or_equal_to: 0 } #Break length is required

  #Date and time validator GEM.
  validates_time :start, :between => ['12:00am', '11:59pm'] #Start time must be a valid time
  validates_time :finish, :between => ['12:00am', '11:59pm'] #End time must be a valid time
  validates_time :finish, :after => lambda {:start} #Finish time must be > than start time (at this stage. Overnight shifts may complicate things).
  
  #Referential Constrains
  belongs_to :user, optional: false #A shift must belong to a user.

end

adnat/app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
    require 'date'
    require 'time'

    # Main Index Page - Where all the magic happens for Shifts.
    # Flexible implementation allows an organisation to be accessed and a shift added to that
    # organisation. 
    # Note: Keeping it this way to allow expansion of features for users to be a part of multiple organisations
    def index
        begin
            @shifts = Shift.all
            #Can require 'json' instead.
            @organisation = Organisation.find(ActiveSupport::JSON.decode(params[:organisation_id]))
            @shift = Shift.new

            # Redirection if User is not a part of the entered organisation.
            begin
                @organisation.users.find(current_user.id)
            rescue
                print "User is not in this organisation - Redirecting"
                redirect_to organisations_path
            end
        rescue
            print "Something went wrong. Possibly wrong organisation id given. Redirecting"
            redirect_to organisations_path
        end 
    end 

    # Show a Single Shift for an organisation. 
    # Unused - Keeping here for consistency.
    def show
        begin
            @organisation = Organisation.find(params[:organisation_id])
        rescue
            print "Bad Organisation ID"
            redirect_to organisations_path
        end 
    end 

    #Edit an existing shift
    def edit
        if check_validity(params[:id])
            @shift = Shift.find(params[:id])
        end
    end

    #Update the model through PATCH call. Called from Edit.html.erb
    #Unsure of best practice here.
    def update
        begin
            @shift = Shift.find(params[:id])

            start_shift_date = params[:shift][:shift_date].to_s.dup
            end_shift_date = params[:shift][:shift_date].to_s.dup
            #Join Shift_date + Start_time together.
            start_time = start_shift_date.concat(' ').concat(params[:shift][:start_time].to_s)
            
            #Join Shift_date + End_time together.
            end_time = end_shift_date.concat(' ').concat(params[:shift][:finish_time].to_s) #Duplicate due to shift date being concat

            if @shift.update(
                :start => DateTime.strptime(start_time, "%m/%d/%Y %H:%M%p"), 
                :finish => DateTime.strptime(end_time, "%m/%d/%Y %H:%M%p"),
                :breaklength => params[:shift][:break_length],
                :user_id => current_user.id)
                print("start: #{@shift.start}")
                flash[:notice] = "Success! Organisation Updated"
                redirect_to organisations_path
            else
                render 'edit'
            end
        rescue
            flash[:alert] = "Error on Shift Creation. Check Entry and Try again"
            render 'edit'
        end
    end
    
    # Handles creation of the shift. Due to nature of dates and times. They are manually
    # constructed and saved within the shifts model
    # Note: Finish time is also Datetime - allows for future expansion of features where
    # end time might finish on a separate date.
    def create
        @shifts = Shift.new()
        start_shift_date = params[:shift][:shift_date].to_s.dup
        end_shift_date = params[:shift][:shift_date].to_s.dup
        
        begin
            #Join Shift_date + Start_time together.
            start_time = start_shift_date.concat(' ').concat(params[:shift][:start_time].to_s)
            
            #Join Shift_date + End_time together.
            end_time = end_shift_date.concat(' ').concat(params[:shift][:end_time].to_s) #Duplicate due to shift date being concat
            
            @shifts.start = DateTime.strptime(start_time, "%m/%d/%Y %H:%M%p")
            @shifts.finish = DateTime.strptime(end_time, "%m/%d/%Y %H:%M%p")
            @shifts.breaklength = params[:shift][:break_length]

            @shifts.user_id = current_user.id

            if @shifts.save
                flash[:notice] = "Success! New Shift Saved"
                redirect_to organisations_path
            else 
                flash[:alert] = "Error on Shift Creation. Check Entry and Try again"
                redirect_to organisations_path
            end 

        rescue
            flash[:alert] = "Error on Shift Creation. Check Entry and Try again"
            redirect_to organisations_path
        end
    end

    # DRYING up some code
    # Checks validity of an organisation. If it doesn't exist. Will just redirect
    private
    def check_validity(id)
        begin
            Shift.find(id)
            return true
        rescue
            print "Bad Shift ID - Redirecting \n"
            redirect_to organisations_path
            return false
        end 
    end
end

adnat/app/helpers/shifts_helper.rb
module ShiftsHelper
end

adnat/app/views/shifts/_form.html.erb
<!-- Date Picker sourced from https://jqueryui.com/datepicker/ -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  //Setup Datepicker functionality.
  $(function() {
    $("#datepicker").datepicker();
  });
</script>
<div class="container"><br>
  <div class="row justify-content-md-center">
    <div class="col col-md-5">
      <%= form_with(model: @shift, local: true) do |shift_form| %>
        <div class="card text-center">
          <div class="card-body" >
            <h3 class="card-title text-center">Edit Shift</h3>
            <p class="card-text text-center"><br>
              <%= shift_form.label :shift_date %>
              <%= shift_form.text_field :shift_date, placeholder: @shift.start.to_date.strftime("%e/%m/%Y"), id: 'datepicker'%><br>
              <%= shift_form.label :start_time %>
              <%= shift_form.text_field :start_time, value: @shift.start.to_time.strftime("%I:%M%p") %>
              <br>
              <%= shift_form.label :finish_time %>
              <%= shift_form.text_field :finish_time, value: @shift.finish.to_time.strftime("%I:%M%p") %>
              <br>
              <%= shift_form.label :break_length %>
              <%= shift_form.text_field :break_length, value: @shift.breaklength %>
              <br>
              <%= shift_form.submit "Update" %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <% if @shift.errors.any? %>
      <div id="error_explanation">
        <% @shift.errors.full_messages.each do |msg| %>
          <span style="color: red"><strong>Notice: </strong></span>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

adnat/app/views/shifts/edit.html.erb
<%= render 'form' %>

adnat/app/views/shifts/index.html.erb
<!-- Date Picker sourced from https://jqueryui.com/datepicker/ -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  function myFunction() {
    // Declare variables
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("search");
    filter = input.value.toUpperCase();
    table = document.getElementById("shiftTable");
    tr = table.getElementsByTagName("tr");
  
    // Loop through all table rows, and hide those who don't match the search query
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[0];
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }
    }
  }
  
  //Setup Datepicker functionality.
  $(function() {
    $("#datepicker").datepicker();
  });
</script>
<div class="container-fluid" >
  <div class="organisation-header">
    <br>
    <span style="font-size: 14pt"><strong> Displaying shifts for <%= @organisation.name %></span></strong>
    <br>
  </div>
  <br>
  <input type="text" id="search" onkeyup="myFunction()" placeholder="Search for names..">
  <table id="shiftTable">
    <tr class="header">
      <th>Employee Name</th>
      <th>Shift date</th>
      <th>Start time</th>
      <th>Finish time</th>
      <th>Break length (minutes)</th>
      <th>Hours Worked</th>
      <th>Shift cost</th>
    </tr>
    <% @organisation.users.each do |user| %>
      <% user.shifts.each do |shift| %>
        <tr onclick="location.href='<%= edit_shift_path(shift.id) %>'">
          <td><%= user.name %></strong></td>
        <td><%=shift.start.to_date.strftime("%e/%m/%Y") %></td>
        <td><%= shift.start.to_time.strftime("%I:%M%p")%></td>
        <td><%= shift.finish.to_time.strftime("%I:%M%p") %></td>
        <td><%= shift.breaklength %></td>
        <% shiftLength = number_with_precision(((shift.finish - shift.start) / 60), :precision => 2)%>
        <% hoursWorked = number_with_precision((shiftLength.to_f - shift.breaklength.to_f), :precision => 2)%>
        <td>
          <%= number_with_precision((hoursWorked.to_f / 60), :precision => 2) %></td>
        <td>$<%= number_with_precision((@organisation.hourly_rate.to_f * (hoursWorked.to_f / 60).to_f), :precision => 2)%></td>
      </tr>
    <% end %>
  <% end %>
  <!-- Create shift section at bottom of table -->
  <tr>
    <%= form_with(model: @shift, local: true) do |form| %>
      <td><%= current_user.name %></td>
      <% if @shift.errors.any? %>
        <div id="error_explanation">
          <% @shift.errors.full_messages.each do |msg| %>
            <span style="color: red"><strong>Notice: </strong></span>
            <%= msg %><br>
          <% end %>
        </div>
      <% end %>
      <td><%= form.text_field :shift_date, id: 'datepicker', placeholder: 'MM/DD/YYYY'%></td>
      <td><%= form.text_field :start_time, value: '7:00am'%></td>
      <td><%= form.text_field :end_time, value: '5:00pm' %></td>
      <td><%= form.text_field :break_length, value: 0%></td>
      <td colspan = '2'><%= form.submit "Update" %></td>
    <% end %>
  </tr>
</table>